-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "user"."users" add column "is_email_verfied" boolean
--  not null default 'false';
