package config

import (
	"os"

	"github.com/joho/godotenv"
)

func init() {

	godotenv.Load("../.env")

	PORT = os.Getenv("PORT")

	HASURA_GRAPHQL_URL = os.Getenv("HASURA_GRAPHQL_URL")

	HASURA_GRAPHQL_ADMIN_SECRET = os.Getenv("HASURA_GRAPHQL_ADMIN_SECRET")

	GIN_MODE = os.Getenv("GIN_MODE")

	ALG = os.Getenv("ALG")

	SEND_GRID_USER_NAME = os.Getenv("SEND_GRID_USER_NAME")

	SEND_GRID_API_KEY = os.Getenv("SEND_GRID_API_KEY")
	SEND_GRID_URL = os.Getenv("SEND_GRID_URL")

	SEND_GRID_SENDER_NAME = os.Getenv("SEND_GRID_SENDER_NAME")
	SEND_GRID_CONTACT_US_TEMPLATE_ID = os.Getenv("SEND_GRID_CONTACT_US_TEMPLATE_ID")

	AWS_SECRET_ACCESS_KEY = os.Getenv("AWS_SECRET_ACCESS_KEY")
	SEND_GRID_SEND_TO_EMAIL = os.Getenv("SEND_GRID_SEND_TO_EMAIL")
	AWS_ACCESS_KEY = os.Getenv("AWS_ACCESS_KEY")
	SEND_GRID_SUBSCRIPTION_TEMPLATE_ID = os.Getenv("SEND_GRID_SUBSCRIPTION_TEMPLATE_ID")
	SEND_GRID_BOOKING_TEMPLATE_ID = os.Getenv("SEND_GRID_BOOKING_TEMPLATE_ID")
	SERVER_PDF_URL = os.Getenv("SERVER_PDF_URL")
	AFRO_URL = os.Getenv("AFRO_URL")
	AFRO_SMS_ACCESS_TOKEN = os.Getenv("AFRO_SMS_ACCESS_TOKEN")
	RESET_PASSWORD_URL = os.Getenv("RESET_PASSWORD_URL")

	JWT_SECRET_KEY = os.Getenv("JWT_SECRET_KEY")
	VERIFICATION_SECRET_KEY = os.Getenv("VERIFICATION_SECRET_KEY")

	// Cloudinary
	CLOUDINARY_CLOUD_NAME = os.Getenv("CLOUDINARY_CLOUD_NAME")
	CLOUDINARY_API_KEY = os.Getenv("CLOUDINARY_API_KEY")
	CLOUDINARY_SECRET = os.Getenv("CLOUDINARY_SECRET")
	DB_PORT = os.Getenv("DB_PORT")
	HOST = os.Getenv("HOST")
	DB_USER = os.Getenv("DB_USER")
	DB_PASSWORD = os.Getenv("DB_PASSWORD")
	DB_NAME = os.Getenv("DB_NAME")

}
