-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "user"."users" add column "email_verify_token_expires_at" timestamptz
--  null;
